What are you shopping for? 0,0,4
Here's your grocery list:
===== ('alcohol', 'white wine') =====
white wine, 1/2 cup

===== ('canned goods', 'crushed tomatoes') =====
crushed tomatoes, 28 oz can + 28 oz can

===== ('canned goods', 'tomato paste') =====
tomato paste, 2 tbsp + 2 tbsp

===== ('condiments/oils', 'olive oil') =====
olive oil, 2 tbsp + 2 tbsp + 2 tbsp

===== ('meat', 'ground beef') =====
ground beef, 1 lb + 1 lb

===== ('pasta', 'linguine') =====
linguine, 8 oz

===== ('pasta', 'spaghetti') =====
spaghetti, 12 oz + 12 oz

===== ('produce', 'garlic') =====
garlic, 3 cloves + 3 cloves + 4 cloves

===== ('produce', 'lemon juice') =====
lemon juice, 2 tbsp

===== ('produce', 'onion') =====
onion, 1 + 1

===== ('produce', 'parsley') =====
parsley, 1/4 cup

===== ('seafood', 'shrimp') =====
shrimp, 1 lb

===== ('spices', 'black pepper') =====
black pepper, to taste + to taste + to taste

===== ('spices', 'dried basil') =====
dried basil, 1 tsp + 1 tsp

===== ('spices', 'dried oregano') =====
dried oregano, 1 tsp + 1 tsp

===== ('spices', 'red pepper flakes') =====
red pepper flakes, 1/2 tsp

===== ('spices', 'salt') =====
salt, to taste + to taste + to taste


Process finished with exit code 0