What are you shopping for? 0,0,4
Here's your grocery list:
===== alcohol =====
white wine, 1/2 cup

===== canned goods =====
crushed tomatoes, 28 oz can + 28 oz can
tomato paste, 2 tbsp + 2 tbsp

===== condiments/oils =====
olive oil, 2 tbsp + 2 tbsp + 2 tbsp

===== meat =====
ground beef, 1 lb + 1 lb

===== pasta =====
linguine, 8 oz
spaghetti, 12 oz + 12 oz

===== produce =====
garlic, 3 cloves + 3 cloves + 4 cloves
lemon juice, 2 tbsp
onion, 1 + 1
parsley, 1/4 cup

===== seafood =====
shrimp, 1 lb

===== spices =====
black pepper, to taste + to taste + to taste
dried basil, 1 tsp + 1 tsp
dried oregano, 1 tsp + 1 tsp
red pepper flakes, 1/2 tsp
salt, to taste + to taste + to taste


Process finished with exit code 0