- Drücken Sie die Taste F1 und tippen Sie den Befehl "create" ein.
- Suchen Sie nach "Create: New File" (oder dem deutschen Äquivalent) und wählen Sie es aus. 
  Dadurch wird eine neue (zunächst noch temporäre) Datei angelegt, in der Sie editieren können.
- Drücken Sie "Strg+S" / "Command+S", um die Datei zu speichern. Ein Fenster öffnet sich. 
  Geben Sie einen passenden Dateinamen mit Endung ein und wählen Sie den Ablageort der Datei
  in Ihrem Arbeitsbereich aus.
