- Drücken Sie die Tastenkombination F1 und tippen Sie den Befehl "create" ein.
- Suchen Sie nach "Create: New File", oder dem Deutschen äquivalent und wählen Sie es aus. Dadurch
wir eine neue temporäre Datei angelegt, die Sie beliebig bearbeiten können.
- Drücken Sie "Strg+S" / "Command+S", um die Datei zu speichern. Ein Fenster öffnet sich. Geben Sie
einen passenden Dateinamen mit Endung ein und wählen Sie den Ablageort der Datei aus.
