- Starten Sie Visual Studio Code und öffnen Sie ihr ProPra Projekt.
- In der linken Seitenleiste sollten Sie ein Symbol erkennen, welches aus Vier Quadraten besteht.
  Klicken Sie darauf werden sie mit der "Extensions"-Seitenleiste begrüßt.
- VSCode sollte ihnen vermutlich schon automatisch vorschlagen die Python-Extension zu 
  installieren. Sollte das nicht der Fall sein geben Sie in die Suche "Python" ein und 
  installieren Sie die offizielle Erweiterung von Microsoft.
- Wenn Sie auf die Python-Extension klicken wird im Hauptfenster die Extension-Seite geladen, dort 
  finden Sie auch eine Anleitung zum korrekten Einrichten ebendieser.
