- Starten Sie Visual Studio Code und öffnen Sie ihr ProPra Projekt über den Explorer-Button auf der
  linken Seitenleiste.
  Wählen Sie "Yes, I trust the authors", falls eine Sicherheitsabfrage erscheint.
- In der linken Seitenleiste sollten Sie ein Symbol erkennen, welches aus Vier Quadraten besteht.
  Klicken Sie darauf, um die "Extensions"-Seitenleiste zu öffnen.
- VSCode sollte ihnen vermutlich schon automatisch vorschlagen die Python-Extension zu 
  installieren. Sollte das nicht der Fall sein geben Sie in die Suche "Python" ein und
  installieren Sie die offizielle Erweiterung von Microsoft.