
[SECTION::submission::snippet]
An dieser Stelle und in diesem Format taucht normalerweise bei jeder Aufgabe
die Beschreibung auf, worin die jeweilige "Abgabe" besteht.

Die Abgabe ist das, was sie bei der Tutor_in zur Durchsicht vorlegen, 
um die Arbeitszeit für die jeweilige Aufgabe gutgeschrieben zu bekommen.
Dafür gibt es mehrere weitgehend standardisierte Formate, 
die aber erst in späteren Aufgaben hier im Basiskapitel besprochen werden.
Und Sie checken die betreffenden Dateien im Versionsverwaltungssystem ein,
was ebenfalls erst in späteren Aufgaben besprochen wird.  
Deshalb passiert hier und jetzt in dieser Aufgabe noch nichts,
sondern Sie holen das nach entsprechender Aufforderung in einer späteren Aufgabe dann nach.

Wie auch in den meisten späteren Aufgaben steht der Hauptteil dessen,
was die Abgabe bestimmt, gar nicht hier in diesem Abschnitt, 
sondern ist oben im Anleitungsabschnitt integriert, weil das Wiederholungen einspart.

Falls das jetzt nicht klar genug geworden ist, arbeiten Sie einfach weiter das Basiskapitel
durch, dann klärt sich das. 
Und wenn doch Fragen offen bleiben: Bitte die Tutor_in fragen!
[ENDSECTION]
