- Starten Sie Visual Studio Code und öffnen Sie ihr ProPra Projekt über den
  Explorer-Button auf der linken Seitenleiste.
  Wählen Sie "Yes, I trust the authors", falls eine Sicherheitsabfrage
  erscheint.
- In der linken Seitenleiste sollten Sie ein Symbol erkennen, welches aus vier
  Quadraten besteht. Klicken Sie darauf, um die "Extensions"-Seitenleiste zu
  öffnen.
- Geben Sie in die Suche "C/C++" ein und installieren Sie die offizielle
  Erweiterung von Microsoft.