Wer etwas anderes als ein aktuelles Debian installiert hat, sollte bestätigen, 
sich einigermaßen sicher damit auszukennen. 
Ubuntu und Mint oder andere Derivate von Debian sind eher unproblematisch.
Aber wer z.B. Arch, Fedora, Suse oder MacOS installiert hat, braucht genügend
Kenntnisse.

Im Zweifelsfall dringend zu Debian raten, **die Studis ansonsten aber gewähren
lassen; bei uns darf jede_r seine schlechten Erfahrungen selbst machen**.
