name: Maintainer

on:
  schedule:
    # Run every Sunday at 03:00 UTC
    - cron: '0 3 * * 0'
  workflow_dispatch:  # Allow manual triggering for testing

jobs:
  check-external-links:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout propra-inf repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Checkout sedrila repository
      uses: actions/checkout@v4
      with:
        repository: fubinf/sedrila
        path: sedrila
        # If sedrila is a private repository, configure:
        # token: ${{ secrets.SEDRILA_ACCESS_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Install all sedrila core dependencies from pyproject.toml
        pip install \
          argparse_subcommand>=1.2 \
          blessed>=1.20 \
          bottle>=0.13 \
          GitPython>=3.1 \
          Jinja2>=3.1 \
          Markdown>=3.7 \
          matplotlib>=3.9 \
          mdx_linkify>=2.1 \
          "numpy<2" \
          pandas>=2.2 \
          Pygments>=2.17 \
          python-gnupg>=0.5.5 \
          PyYAML>=6.0 \
          requests>=2.32 \
          rich>=13.7
    
    - name: Verify environment
      run: |
        python --version
        ls -la
        ls -la sedrila/py/
    
    - name: Run link checker
      run: |
        python sedrila/py/sedrila.py maintainer --check-links
      continue-on-error: false
    
    - name: Upload link check reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: link-check-reports
        path: |
          link_check_report.json
          link_check_report.md
        retention-days: 90
    
    - name: Display report summary
      if: always()
      run: |
        echo "=== Link Check Summary ==="
        if [ -f link_check_report.json ]; then
          echo "Reports generated successfully:"
          ls -la link_check_report.*
          echo ""
          echo "JSON report preview:"
          head -20 link_check_report.json
        else
          echo "No reports found"
        fi

